server:
  port: 9100

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/testdb-auth
    username: postgres
    password: postgresql
    initialization-mode: never

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  jackson:
    serialization:
      INDENT_OUTPUT: true
